name: Check Pull Request

on:
  pull_request:
    branches: [ "master", "dev/**" ]
permissions:
  contents: read
  actions: read
  checks: write
env:
  GITHUB_USERNAME: "CarverBot"
  GITHUB_TOKEN: ${{ secrets.OPTIMIZATION_TOKEN }}

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    name: Assign a reviewer
    steps:
      - name: Assign task to a Reviewer
        uses: hkusu/review-assign-action@v1
        with:
          assignees: Pabilo8
          github-token: ${{ secrets.OPTIMIZATION_TOKEN }}

  check:
    runs-on: ubuntu-latest
    name: Compile and Run Checks
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Prepare Workspace
        run: chmod +x gradlew ; ./gradlew setupDecompWorkspace

      - name: Check for Compilation
        run: ./gradlew compileJava

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Test Report
        uses: phoenix-actions/test-reporting@v15
        id: test-report               # Set ID reference for step
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Tests            # Name of the check run which will be created
          path: build/test-results/test/TEST-*.xml    # Path to test results
          reporter: java-junit        # Format of test results
          token: ${{ secrets.OPTIMIZATION_TOKEN }}

  notify-discord:
    runs-on: ubuntu-latest
    name: Notify Discord
    steps:
      - name: Notify Internal Discord
        uses: sebastianpopp/discord-action@releases/v2
        with:
          webhook: ${{ secrets.WH_PR_PRIVATE }}
          message: "[@${{ github.event.pull_request.user.login }}](<https://github.com/${{ github.event.pull_request.user.login }}>) has contributed to Engineers' Cause with [${{ github.event.pull_request.title }}](<https://github.com/${{ github.repository }}/issues/${{ github.event.pull_request.number }}>)."

      - name: Notify Public Discord
        if: ${{ github.event.pull_request.user.login != 'CarverBot' }}
        uses: sebastianpopp/discord-action@releases/v2
        with:
          webhook: ${{ secrets.WH_PR_PUBLIC }}
          message: "[@${{ github.event.pull_request.user.login }}](<https://github.com/${{ github.event.pull_request.user.login }}>) has contributed to Engineers' Cause with [${{ github.event.pull_request.title }}](<https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}>)."