name: Notify Discord on Push

on:
  push: #Trigger On Push
    branches: [ "master" ]

jobs:
  notify-discord:
    continue-on-error: true
    name: Optimize Assets
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: 'CarverBot'
      GITHUB_TOKEN: ${{ secrets.OPTIMIZATION_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Properties File
        id: rp
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'mcmod_Name mcmod_Developer mcmod_URL'

      - name: Notify Discord
        env:
          WEBHOOK: ${{ secrets.DISCORD_COMMITS_WEBHOOK }}
          MOD_NAME: ${{ steps.rp.outputs.mcmod_Name }}
          MOD_DEVOLOPER: ${{ steps.rp.outputs.mcmod_Developer }}
          MOD_URL: ${{ steps.rp.outputs.mcmod_URL }}
          COMMIT_FROM: ${{ steps.rp.outputs.mcmod_URL }}
          COMMIT_TO: ${{ steps.rp.outputs.mcmod_URL }}
        run: chmod -R a+rX ./gradle/tools/* ; bash ./gradle/tools/discord_commit.sh -i